[build]
builder = "nixpacks"

[deploy]
startCommand = "go run main.go"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
GIN_MODE = "release" 